python train_lora_flax.py \
--pretrained_model_name_or_path runwayml/stable-diffusion-v1-5 \
--instance_data_dir ../aardman/imgs \
--hub_model_id gigant/lora-aardman-sd15 \
--mixed_precision fp16 \
--train_batch_size 1 \
--revision flax \
--output_dir "lora_output" \
--learning_rate 3e-5 \
--max_train_steps 500 \
--push_to_hub \
--num_train_epochs 1
